# Generated by Django 3.0.4 on 2020-03-22 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConfirmedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('country', models.CharField(max_length=100)),
                ('count', models.IntegerField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='DeadData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('country', models.CharField(max_length=100)),
                ('count', models.IntegerField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='RecoveredData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('country', models.CharField(max_length=100)),
                ('count', models.IntegerField(default=0.0)),
            ],
        ),
    ]
