# Generated by Django 3.0.4 on 2020-04-25 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField()),
                ('country', models.CharField(max_length=100)),
                ('count', models.IntegerField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='CovidData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateField()),
                ('country', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('ibge_id', models.CharField(max_length=50)),
                ('new_deaths', models.IntegerField(blank=True, default=None, null=True)),
                ('deaths', models.IntegerField(blank=True, default=None, null=True)),
                ('new_cases', models.IntegerField(blank=True, default=None, null=True)),
                ('total_cases', models.IntegerField(blank=True, default=None, null=True)),
                ('new_recovered', models.IntegerField(blank=True, default=None, null=True)),
                ('recovered', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeadData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField()),
                ('country', models.CharField(max_length=100)),
                ('count', models.IntegerField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='ImportsUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('endpoint', models.CharField(max_length=1024)),
                ('columns', models.CharField(max_length=1200)),
                ('rows_count', models.IntegerField(blank=True, default=None, null=True)),
                ('cols_count', models.IntegerField(blank=True, default=None, null=True)),
                ('total_import_time', models.FloatField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecoveredData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField()),
                ('country', models.CharField(max_length=100)),
                ('count', models.IntegerField(default=0.0)),
            ],
        ),
        migrations.AddIndex(
            model_name='recovereddata',
            index=models.Index(fields=['timestamp'], name='api_recover_timesta_f9b032_idx'),
        ),
        migrations.AddIndex(
            model_name='importsupdate',
            index=models.Index(fields=['created_at'], name='api_imports_created_b6c6b8_idx'),
        ),
        migrations.AddIndex(
            model_name='deaddata',
            index=models.Index(fields=['timestamp'], name='api_deaddat_timesta_0f412a_idx'),
        ),
        migrations.AddIndex(
            model_name='coviddata',
            index=models.Index(fields=['timestamp'], name='api_covidda_timesta_49addd_idx'),
        ),
        migrations.AddIndex(
            model_name='confirmeddata',
            index=models.Index(fields=['timestamp'], name='api_confirm_timesta_d7b034_idx'),
        ),
    ]
