# Generated by Django 3.0.4 on 2020-04-05 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='confirmeddata',
            index=models.Index(fields=['created_at'], name='api_confirm_created_c439d0_idx'),
        ),
        migrations.AddIndex(
            model_name='deaddata',
            index=models.Index(fields=['created_at'], name='api_deaddat_created_985b78_idx'),
        ),
        migrations.AddIndex(
            model_name='recovereddata',
            index=models.Index(fields=['created_at'], name='api_recover_created_301a05_idx'),
        ),
    ]
